// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6rwzBZmzS3-ga-9n2vAxtINXFXCC6TcI',
    appId: '1:416259209174:web:02dc6a6e21117fecbd9677',
    messagingSenderId: '416259209174',
    projectId: 'eduquiz-interactive',
    authDomain: 'eduquiz-interactive.firebaseapp.com',
    storageBucket: 'eduquiz-interactive.firebasestorage.app',
    measurementId: 'G-WQSH5XH4DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6jeULC19lK2d0wBMc8QyfOZRCD3RSmRE',
    appId: '1:416259209174:android:d16933ac2f6794adbd9677',
    messagingSenderId: '416259209174',
    projectId: 'eduquiz-interactive',
    storageBucket: 'eduquiz-interactive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-I2YkBe4Z8JULu-6FCRBJ_VzwepJkv0',
    appId: '1:416259209174:ios:9f9986989933ae73bd9677',
    messagingSenderId: '416259209174',
    projectId: 'eduquiz-interactive',
    storageBucket: 'eduquiz-interactive.firebasestorage.app',
    iosBundleId: 'com.example.eduquizInteractive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu-I2YkBe4Z8JULu-6FCRBJ_VzwepJkv0',
    appId: '1:416259209174:ios:9f9986989933ae73bd9677',
    messagingSenderId: '416259209174',
    projectId: 'eduquiz-interactive',
    storageBucket: 'eduquiz-interactive.firebasestorage.app',
    iosBundleId: 'com.example.eduquizInteractive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6rwzBZmzS3-ga-9n2vAxtINXFXCC6TcI',
    appId: '1:416259209174:web:82ba7da1be104345bd9677',
    messagingSenderId: '416259209174',
    projectId: 'eduquiz-interactive',
    authDomain: 'eduquiz-interactive.firebaseapp.com',
    storageBucket: 'eduquiz-interactive.firebasestorage.app',
    measurementId: 'G-9XEFYYW48C',
  );
}
